[package]
name = "bdkct"
version = "0.3.257-dev"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
bdk = { version = "0.30.2", features = [ "esplora" ] }
bdk_esplora = { version = "*", features = ["blocking"] }
bdk_file_store = "*"
bdk_wallet = "*"
anyhow = "*"
